SET NAMES 'UTF8';
DROP DATABASE if exists web;
CREATE DATABASE IF NOT EXISTS web DEFAULT CHARSET='UTF8';
USE web;

GRANT ALL PRIVILEGES ON web.* TO 'web'@'%' IDENTIFIED BY 'web123!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON web.* TO 'web'@'127.0.0.1' IDENTIFIED BY 'web123!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON web.* TO 'web'@'localhost' IDENTIFIED BY 'web123!' WITH GRANT OPTION;

GRANT SELECT ON mysql.proc TO 'web'@'localhost';
GRANT SELECT ON mysql.proc TO 'web'@'127.0.0.1';
GRANT SELECT ON mysql.proc TO 'web'@'%';

FLUSH PRIVILEGES;